name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "lua/**"
      - "plugin/**"
      - ".mise/tasks/**"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
    contents: write

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Install Neovim
              run: sudo apt-get update && sudo apt-get install -y neovim

            - name: Fetch mini.nvim
              run: git clone --depth 1 https://github.com/echasnovski/mini.nvim "${GITHUB_WORKSPACE}/.ci/mini.nvim"

            - name: Generate docs
              env:
                MINI_PATH: ${{ github.workspace }}/.ci/mini.nvim
              run: make docs

            - name: Commit docs
              uses: stefanzweifel/git-auto-commit-action@v7
              with:
                commit_message: "chore(docs): regenerate vim help"