name: Lint

on:
    push:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        concurrency:
            group: ${{ format('{0}:{1}:{2}', github.workflow, github.repository, github.ref) }}
            cancel-in-progress: true
        permissions:
            contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Install Luacheck
              run: sudo apt-get update && sudo apt-get install -y lua-check
            
            - name: Run Luacheck
              run: luacheck "lua/ plugin/ tests/"